name: Update Version
on:
  schedule:
    - cron: '* 0 * * *'
  workflow_dispatch:
  repository_dispatch:  

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    steps:

    - name: Get latest release
      uses: rez0n/actions-github-release@main
      id: version
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'bertvandepoel/tabby'
        type: 'latest'
    
    - name: Get current version
      id: current_version
      run: echo ::set-output name=version::$(curl https://raw.githubusercontent.com/parksauce/tabby/main/params/VERSION)
    outputs:
      currentVersion: ${{ steps.current_version.outputs.version }}

    - name: Format version
      id: latest
      run: "version='${{ steps.version.outputs.release }}' && echo ::set-output name=version::${version/'v'/''} && mkdir params && echo ${version/'v'/''} > params/VERSION"
    outputs:
      latestVersion: ${{ steps.latest.outputs.version }}
      
    - run: echo ${{ steps.latest.outputs.version }} && echo ${{ steps.current_version.outputs.version }}

    - name: Compare versions
      if: $((${{ steps.latest.outputs.version }})) > $((${{ steps.current_version.outputs.version }}))
      uses: test-room-7/action-update-file@v1
      with:
          file-path: params/VERSION
          commit-msg: bot update
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    needs: current_version,latest
    name: Build Containers
    runs-on: ubuntu-latest
    steps:

    - run: echo ${{ needs.latest.outputs.latestVersion }} && echo ${{ needs.current_version.outputs.latestVersion }}

    - name: Run Docker Build
      if: $((${{ needs.latest.outputs.latestVersion }})) > $((${{ needs.current_version.outputs.latestVersion }}))
      uses: parksauce/tabby/.github/workflows/build.yml@main